//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClayData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public string lot { get; set; }
        public int offset { get; set; }
        public int pressure { get; set; }
        public System.DateTime date { get; set; }
        public string component { get; set; }
        public string colorbound { get; set; }
        public string quality { get; set; }
        public string performance { get; set; }
        public int result { get; set; }
        public int timecode { get; set; }
        public int layout { get; set; }
    }
}
